import { Bot } from 'lucide-react'
import { getTemplateLabel } from '@/lib/whatsappTemplates'

type Props = {
  /** Value from tasks.automation_type — typically a template name like
   *  `visite_confirmation_j_moins_1`. Null/empty renders nothing. */
  automationType: string | null | undefined
  /** Optional className for sizing/margin tweaks in the caller. */
  className?: string
}

/**
 * Small "🤖 Confirmation visite J-1" pill that identifies a task as
 * auto-generated by the automation engine (i.e. dispatchAutomation
 * wrote it into `tasks` because the tenant has no active WhatsApp).
 * Agents need to tell these apart from manual tasks at a glance so
 * they know they'll have a pre-filled wa.me deeplink handy.
 */
export function AutomationBadge({ automationType, className }: Props) {
  if (!automationType) return null
  const label = getTemplateLabel(automationType)
  return (
    <span
      className={`inline-flex items-center gap-1 rounded-full border border-[#7C3AED]/30 bg-[#7C3AED]/10 px-2 py-0.5 text-[10px] font-semibold text-[#7C3AED] ${className ?? ''}`}
      title={`Tache generee automatiquement — ${label}`}
    >
      <Bot className="h-3 w-3" />
      {label}
    </span>
  )
}
